name: ttsfood
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.2.5

  carousel_slider: ^4.2.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  provider: ^6.1.1

  flutter_html: ^3.0.0-beta.2   # ← Thêm gói xử lý HTML ở đây


  font_awesome_flutter: ^10.7.0 # ← thêm dòng này
  html: ^0.15.6
  webview_flutter: ^4.2.2
  webview_flutter_android: ^3.10.0
  shared_preferences: ^2.2.2

  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
