name: ttsfood
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  provider: ^6.1.1
  font_awesome_flutter: ^10.7.0
  flutter_html: ^3.0.0-beta.2   # ← Thêm gói xử lý HTML ở đây

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
